package com.tzy.api.spider.dto;

import lombok.Data;

import java.util.List;


@Data
public class AwemeList {

    private String aweme_id;
    private String desc;
    private long create_time;
    private Author author;
    //    private Music music;
//    private String shoot_way;
    private Video video;
    private String share_url;
    //    private Long user_digged;
//    private Statistics statistics;
//    private Status status;
//    private Long media_type;
//    private List<Text_extra> text_extra;
//    private Long is_top;
//    private EntertainmentProductInfo entertainment_product_info;
//    private ShareInfo share_info;
//    private boolean can_cache_to_local;
//    private String video_labels;
//    private boolean mark_largely_following;
//    private boolean is_ads;
//    private Long duration;
//    private Long aweme_type;
//    private Long flash_mob_trends;
//    private GameTagInfo game_tag_info;
//    private String image_infos;
//    private RiskInfos risk_infos;
//    private FriendRecommendInfo friend_recommend_info;
//    private String jump_tab_info_list;
//    private String position;
//    private String uniqid_position;
//    private String comment_list;
//    private long author_user_id;
//    private AwemeListenStruct aweme_listen_struct;
//    private List<String> geofencing;
//    private String trends_infos;
//    private Long video_share_edit_status;
//    private String region;
//    private String video_text;
//    private Long image_crop_ctrl;
//    private Long collect_stat;
//    private String label_top_text;
//    private List<String> promotions;
//    private String group_id;
//    private boolean prevent_download;
//    private String nickname_position;
//    private String challenge_position;
//    private XiguaBaseInfo xigua_base_info;
//    private DistributeCircle distribute_circle;
//    private VideoGameDataChannelConfig video_game_data_channel_config;
//    private String long_video;
//    private Long original;
//    private boolean is_use_music;
//    private String dislike_dimension_list_v2;
//    private String mv_info;
//    private String Longeraction_stickers;
//    private String create_scale_type;
//    private String origin_comment_ids;
//    private String commerce_config_data;
//    private String origin_duet_resource_uri;
//    private VideoControl video_control;
//    private AwemeControl aweme_control;
//    private String aweme_type_tags;
//    private PublishPlusAlienation publish_plus_alienation;
//    private Long activity_video_type;
//    private boolean enable_comment_sticker_rec;
//    private String anchors;
//    private String hybrid_label;
//    private String geofencing_regions;
//    private Long personal_page_botton_diagnose_style;
//    private AwemeAcl aweme_acl;
//    private PlayProgress play_progress;
//    private Long is_story;
//    private String caption;
//    private String slides_music_beats;
//    private ComponentControl component_control;
//    private String cover_labels;
//    private String chapter_bar_color;
//    private Long boost_status;
//    private Long guide_btn_type;
//    private Long friend_Longeraction;
//    private String reply_smart_emojis;
    private List<Images> images;
    //    private String relation_labels;
//    private Long is_24_story;
//    private ImpressionData impression_data;
//    private String item_title;
//    private String yumme_recreason;
//    private String libfinsert_task_id;
//    private String social_tag_list;
//    private SuggestWords suggest_words;
//    private ShowFollowButton show_follow_button;
//    private boolean duet_aggregate_in_music_tab;
//    private boolean is_duet_sing;
//    private CommentPermissionInfo comment_permission_info;
//    private String original_images;
//    private SeriesPaidInfo series_paid_info;
//    private String img_bitrate;
//    private long comment_gid;
//    private ImageAlbumMusicInfo image_album_music_info;
//    private List<Video_tag> video_tag;
//    private Long is_collects_selected;
//    private String chapter_list;
//    private FeedCommentConfig feed_comment_config;
//    private boolean is_image_beat;
//    private String dislike_dimension_list;
//    private String standard_bar_info_list;
//    private PhotoSearchEntrance photo_search_entrance;
//    private DanmakuControl danmaku_control;
//    private boolean is_life_item;
//    private String image_list;
//    private String component_info_v2;
//    private ItemWarnNotification item_warn_notification;
//    private String origin_text_extra;
//    private Long disable_relation_bar;
//    private String packed_clips;
//    private VtagSearch vtag_search;
//    private Long author_mask_tag;
//    private Long user_recommend_status;
//    private Long collection_corner_mark;
//    private ImageComment image_comment;
//    private VisualSearchInfo visual_search_info;
//    private String tts_id_list;
//    private String ref_tts_id_list;
//    private String voice_modify_id_list;
//    private String ref_voice_modify_id_list;
//    private String authentication_token;
    private CooperationInfo cooperation_info;


}